### ISSUE TITLE
Can we solve the problem? every pc(with one IP) can't post too many request to Google to get result...

### ISSUE THREAD

**Issue by WeAreGM** [ZiJie-Li/googleSearchParser#1]
I try use google custom search engine. and i find this problem...
In China,people can't access google.com...so ,I want use my vps(which in hongkong, and people can access the website in that vps) to parser google's result..

but when I do this...I find this problem..
- -、

我尝试用谷歌自定义搜索，然后我发现了标题所述的那个问题
在中国，不能访问谷歌。。所以，我想用我的vps(vps位于香港，大陆可以访问这台vps上的站点)解析谷歌的搜索结果，然后展示在站点上，这样大陆就能获取到谷歌的搜索结果了
但是当我开始这么做的时候，我发现了标题所述的那个问题。。。
- -、

**Comment by ZiJie-Li** [comment]
This problem has always existed,one IP post too many request been as like bot
u can try Google Web Search API
